/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx 
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CS: THREE.Mesh
    SUB_CS: THREE.Mesh
  }
  materials: {}
}

export function BO_CS(props: JSX.IntrinsicElements['group'] & { children?: React.ReactNode, secondary?: React.ReactNode }) {
  const { nodes } = useGLTF('models/mfb/4performance-tip/CS.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CS.geometry} material={nodes.CS.material}>
        <mesh geometry={nodes.SUB_CS.geometry} material={nodes.SUB_CS.material}>
          {props.secondary}
        </mesh>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('models/mfb/4performance-tip/CS.glb')
