/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BO_DS: THREE.Mesh
  }
  materials: {}
}

export function BO_DS(props: JSX.IntrinsicElements['group'] & {children: React.ReactNode}) {
  const { nodes } = useGLTF('/models/mfb/4performance-tip/BO_DS.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="BO_DS"
        geometry={nodes.BO_DS.geometry}
        material={nodes.BO_DS.material}
        userData={{ name: 'BO_DS' }}
      >
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/4performance-tip/BO_DS.glb')
