/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BO_ES: THREE.Mesh
    BO_SUB_ES: THREE.Mesh
  }
  materials: {}
}

export function BO_ES(props: JSX.IntrinsicElements['group'] & { children?: React.ReactNode, secondary?: React.ReactNode }) {
  const { nodes } = useGLTF('/models/mfb/4performance-tip/BO_ES.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="BO_ES"
        geometry={nodes.BO_ES.geometry}
        material={nodes.BO_ES.material}>
        <mesh
          name="BO_SUB_ES"
          geometry={nodes.BO_SUB_ES.geometry}
          material={nodes.BO_SUB_ES.material}
        >
          {props.secondary}
        </mesh>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/4performance-tip/BO_ES.glb')
