/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    R2F: THREE.Mesh
    SUB_R2F: THREE.Mesh
  }
  materials: {}
}

export function BO_R2F(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode, secondary?: React.ReactNode}) {
  const { nodes } = useGLTF('models/mfb/4performance-tip/R2F.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.R2F.geometry} material={nodes.R2F.material}>
        <mesh geometry={nodes.SUB_R2F.geometry} material={nodes.SUB_R2F.material}>
          {props.secondary}
        </mesh>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('models/mfb/4performance-tip/R2F.glb')
