/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    ES: THREE.Mesh
    ES001: THREE.Mesh
  }
  materials: {}
}

export function ES({children, ...props}: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/4performance-tip/ES.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="ES"
        geometry={nodes.ES.geometry}
        material={nodes.ES.material}
        userData={{ name: 'ES' }}>
        <mesh
          name="ES001"
          geometry={nodes.ES001.geometry}
          material={nodes.ES001.material}
          userData={{ name: 'ES.001' }}
        >
          {props.clear ? <MeshTransmissionMaterial roughness={0.3} transmission={0.2} resolution={32} samples={1} /> : <meshStandardMaterial />}
        </mesh>
        {children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/4performance-tip/ES.glb')
