/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    SD: THREE.Mesh
  }
  materials: {}
}

export function SD({children, ...props}: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/4performance-tip/SD.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="SD"
        geometry={nodes.SD.geometry}
        material={nodes.SD.material}
        userData={{ name: 'SD' }}
      >
        {children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/4performance-tip/SD.glb')
