/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    facebolt: THREE.Mesh
  }
  materials: {}
}

export function FaceBolt({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/Facebolt.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="facebolt"
        castShadow
        receiveShadow
        geometry={nodes.facebolt.geometry}
        material={nodes.facebolt.material}
        userData={{ name: 'facebolt' }}
      >
        {children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/Facebolt.glb')
