/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mfb/2fusion-wheel/gravity.glb --transform -S 
Files: public/models/mfb/2fusion-wheel/gravity.glb [60.56KB] > /home/hardik/beyblade/gravity-transformed.glb [21.16KB] (65%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gravity-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MW_Gravity.geometry} material={nodes.MW_Gravity.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gravity-transformed.glb')
