/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    flame: THREE.Mesh
  }
  materials: {}
}

export function MW_Flame(props: JSX.IntrinsicElements['group'] & { children?: React.ReactNode }) {
  const { nodes } = useGLTF('/models/mfb/2fusion-wheel/flame.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="flame"
        geometry={nodes.flame.geometry}
        material={nodes.flame.material}
        userData={{ name: 'flame' }}
      >
        <group
          name="attach_bolt"
          position={[0, 2.878, 0]}
          userData={{ name: 'attach_bolt' }}
        />
        <group
          name="attach_ring"
          position={[0, -1.982, 0]}
          userData={{ name: 'attach_ring' }}
        />
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/2fusion-wheel/flame.glb')

