/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        MW_Hades: THREE.Mesh
    }
    materials: {}
}

export function MW_Hades(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode}) {
    const { nodes } = useGLTF('/models/mfb/2fusion-wheel/MW_Hades.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                name="MW_Hades"
                geometry={nodes.MW_Hades.geometry}
                material={nodes.MW_Hades.material}
                userData={{ name: 'MW_Hades' }}
            >
                {props.children}
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/mfb/2fusion-wheel/MW_Hades.glb')
