/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    poison: THREE.Mesh
  }
  materials: {}
}

export function MW_Poison(props: JSX.IntrinsicElements['group'] & { children?: React.ReactNode }) {
  const { nodes } = useGLTF('/models/mfb/2fusion-wheel/poison.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
        <mesh
          name="poison"
          geometry={nodes.poison.geometry}
          material={nodes.poison.material}
          userData={{ name: 'poison' }}
        >
          {props.children}
        </mesh>
        <group
          name="attach_bolt"
          position={[0, 2.908, 0]}
          userData={{ name: 'attach_bolt' }}
        />
        <group
          name="attach_ring"
          position={[0, -1.952, 0]}
          userData={{ name: 'attach_ring' }}
        />
    </group>
  )
}

useGLTF.preload('/models/mfb/2fusion-wheel/poison.glb')
