/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    ray: THREE.Mesh
  }
  materials: {}
}

export function MW_Ray(props: JSX.IntrinsicElements['group'] & {children: React.ReactNode}) {
  const { nodes } = useGLTF('models/mfb/2fusion-wheel/ray.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ray.geometry} material={nodes.ray.material}>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('models/mfb/2fusion-wheel/ray.glb')
