/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { type JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    ['145']: THREE.Mesh
  }
  materials: {}
}

export function _145(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/3spin-track/145.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="145"
        geometry={nodes['145'].geometry}
        material={nodes['145'].material}
        userData={{ name: '145' }}>
        <group name="attach_tip" position={[0, -11, 0]} userData={{ name: 'attach_tip' }} />
        <group name="attach_wheel" userData={{ name: 'attach_wheel' }} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/3spin-track/145.glb')
