/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['230']: THREE.Mesh
  }
  materials: {}
}

export function _230(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/3spin-track/230.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="230"
        geometry={nodes['230'].geometry}
        material={nodes['230'].material}
        userData={{ name: '230' }}
      >
        <MeshTransmissionMaterial transmissionSampler samples={1} resolution={256} transmission={0.2} roughness={0.3} />
      </mesh>
      <group name="attach_tip" position={[0, -19.5, 0]} userData={{ name: 'attach_tip' }} />
      <group name="attach_wheel" userData={{ name: 'attach_wheel' }} />
    </group>
  )
}

useGLTF.preload('/models/mfb/3spin-track/230.glb')
