/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SW145: THREE.Mesh
    wing: THREE.Mesh
  }
  materials: {}
}

export function SW145(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/3spin-track/SW145.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="SW145"
        geometry={nodes.SW145.geometry}
        material={nodes.SW145.material}
        userData={{ name: 'SW145' }}>
        <mesh
          name="wing"
          geometry={nodes.wing.geometry}
          material={nodes.wing.material}
          position={[0, -8.038, 0]}
          userData={{ name: 'wing' }}
        />
        <group name="attach_tip" position={[0, -11, 0]} userData={{ name: 'attach_tip' }} />
        <group name="attach_wheel" userData={{ name: 'attach_wheel' }} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/3spin-track/SW145.glb')
