/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
    nodes: {
        T125: THREE.Mesh
    }
    materials: {}
}

export function T125(props: JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF('/models/mfb/3spin-track/T125.glb') as unknown as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                name="T125"
                geometry={nodes.T125.geometry}
                material={nodes.T125.material}
                userData={{ name: 'T125' }}>
                <group name="attach_tip" position={[0, -9, 0]} userData={{ name: 'attach_tip' }} />
                {/* <group name="attach_wheel" userData={{ name: 'attach_wheel' }} /> */}
                <meshStandardMaterial />
                <MeshTransmissionMaterial samples={1} resolution={128} transmission={0.3} roughness={0.3} />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/mfb/3spin-track/T125.glb')
