/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        TR_145: THREE.Mesh
    }
    materials: {}
}

export function TR_145(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode, secondary?: React.ReactNode}) {
    const { nodes } = useGLTF('/models/mfb/3spin-track/TR_145.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh name="TR_145" geometry={nodes.TR_145.geometry} material={nodes.TR_145.material}>
                {props.children}        
            </mesh>
            <group name="attach_tip" position={[0, -11, 0]} userData={{ name: 'attach_tip' }} />
        </group>
    )
}

useGLTF.preload('/models/mfb/3spin-track/TR_145.glb')
