/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        ['230']: THREE.Mesh
    }
    materials: {}
}

export function TR_230(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode, secondary?: React.ReactNode}) {
    const { nodes } = useGLTF('/models/mfb/3spin-track/TR_230.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh name="230" geometry={nodes['230'].geometry} material={nodes['230'].material}>
                {props.children}
            </mesh>
            <group name="attach_tip" position={[0, -19.523, 0]} />
        </group>
    )
}

useGLTF.preload('/models/mfb/3spin-track/TR_230.glb')
