/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        TR_BD145: THREE.Mesh
        disk: THREE.Mesh
    }
    materials: {}
}

export function TR_BD145(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode, secondary?: React.ReactNode, mode?:string}) {
    const { nodes } = useGLTF('/models/mfb/3spin-track/TR_BD145.glb') as unknown as GLTFResult;
    const diskPos: [number, number, number] = props.mode === "Stamina" ? [0, -3.569, 0] : [0, -8.783, 0];
    const diskRot: [number, number, number] = props.mode === "Stamina" ? [0, 0, 0] : [Math.PI,0,0];
    return (
        <group {...props} dispose={null}>
          <mesh
            name="TR_BD145"
            geometry={nodes.TR_BD145.geometry}
            material={nodes.TR_BD145.material}
            userData={{ name: 'TR_BD145' }}>
            <mesh
              name="disk"
              geometry={nodes.disk.geometry}
              material={nodes.disk.material}
              position={diskPos}
              rotation={diskRot}
              userData={{ name: 'disk' }}
            >
                {props.secondary}
            </mesh>
            {props.children}
            <group name="attach_tip" position={[0, -11, 0]} userData={{ name: 'attach_tip' }} />
          </mesh>
        </group>
      )
}

useGLTF.preload('/models/mfb/3spin-track/TR_BD145.glb')
