/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    TR_D125: THREE.Mesh
  }
  materials: {}
}

export function TR_D125(props: JSX.IntrinsicElements['group'] & {children: React.ReactNode}) {
  const { nodes } = useGLTF('models/mfb/3spin-track/TR_D125.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TR_D125.geometry} material={nodes.TR_D125.material}>
        {props.children}
        <group name="attach_tip" position={[0, -9, 0]} userData={{ name: 'attach_tip' }} />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/mfb/3spin-track/TR_D125.glb')
