/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TR_SW145: THREE.Mesh
    wing: THREE.Mesh
  }
  materials: {}
}

export function TR_SW145(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode, secondary?: React.ReactNode, mode?: string}) {
  const { nodes } = useGLTF('/models/mfb/3spin-track/TR_SW145.glb') as unknown as GLTFResult
  const wingRot: [number, number, number] = props.mode === "Attack" ? [Math.PI,0,0] : [0,0,0];
  return (
    <group {...props} dispose={null}>
      <mesh
        name="SW145"
        geometry={nodes.TR_SW145.geometry}
        material={nodes.TR_SW145.material}
        userData={{ name: 'SW145' }}
      >
        <mesh
          name="wing"
          geometry={nodes.wing.geometry}
          material={nodes.wing.material}
          position={[0, -8.038, 0]}
          rotation={wingRot}
          userData={{ name: 'wing' }}
        >
          {props.secondary}
        </mesh>
        {props.children}
        <group name="attach_tip" position={[0, -11, 0]} userData={{ name: 'attach_tip' }} />
        <group name="attach_wheel" userData={{ name: 'attach_wheel' }} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/3spin-track/TR_SW145.glb')
