/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        TR_T125: THREE.Mesh
    }
    materials: {}
}

export function TR_T125(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode, secondary?: React.ReactNode}) {
    const { nodes } = useGLTF('/models/mfb/3spin-track/TR_T125.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh name="TR_T125" geometry={nodes.TR_T125.geometry} material={nodes.TR_T125.material}>
                {props.children}
                <group name="attach_tip" position={[0, -9, 0]} userData={{ name: 'attach_tip' }} />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/mfb/3spin-track/TR_T125.glb')