/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    TR_W105: THREE.Mesh
  }
  materials: {}
}

export function TR_W105(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode}) {
  const { nodes } = useGLTF('models/mfb/3spin-track/TR_W105.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TR_W105.geometry} material={nodes.TR_W105.material}>
        {props.children}
      </mesh>
      <group name="attach_tip" position={[0, -7.009, 0]} />
    </group>
  )
}

useGLTF.preload('models/mfb/3spin-track/TR_W105.glb')
