/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    byxis: THREE.Mesh
  }
  materials: {}
}

export function Byxis(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/1energy-ring/byxis.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="byxis" geometry={nodes.byxis.geometry} material={nodes.byxis.material} />
    </group>
  )
}

useGLTF.preload('/models/mfb/1energy-ring/byxis.glb')
