/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
    nodes: {
        CW_Kerbecs: THREE.Mesh
    }
    materials: {}
}

export function CW_Kerbecs(props: JSX.IntrinsicElements['group'] & { children: React.ReactNode }) {
    const { nodes } = useGLTF('/models/mfb/1energy-ring/CW_Kerbecs.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                name="CW_Kerbecs"
                geometry={nodes.CW_Kerbecs.geometry}
                material={nodes.CW_Kerbecs.material}
                userData={{ name: 'CW_Kerbecs' }}
            >
                {props.children}
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/mfb/1energy-ring/CW_Kerbecs.glb')
