/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\mfb\1energy-ring\CW_Lacerta.glb --transform -S 
Files: .\public\models\mfb\1energy-ring\CW_Lacerta.glb [28.41KB] > C:\Users\HARDIK\mybeycombo\CW_Lacerta-transformed.glb [15.66KB] (45%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
    nodes: {
        CW_Lacerta: THREE.Mesh
    }
    materials: {}
}

export function CW_Lacerta(props: JSX.IntrinsicElements['group'] & { children: React.ReactNode }) {
  const { nodes } = useGLTF('/models/mfb/1energy-ring/CW_Lacerta.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh name='CW_Lacerta' 
        geometry={nodes.CW_Lacerta.geometry} 
        material={nodes.CW_Lacerta.material} 
        rotation={[Math.PI / 2, 0, 0]} 
        userData={{ name: 'CW_Lacerta' }}
      >
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/CW_Lacerta-transformed.glb')
