/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    pegasus2: THREE.Mesh
  }
  materials: {}
}

export function CW_Pegasus2(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode}) {
  const { nodes } = useGLTF('models/mfb/1energy-ring/pegasus2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pegasus2.geometry} material={nodes.pegasus2.material}>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('models/mfb/1energy-ring/pegasus2.glb')
