/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    serpent: THREE.Mesh
  }
  materials: {}
}

export function CW_Serpent(props: JSX.IntrinsicElements['group'] & { children?: React.ReactNode }) {
  const { nodes } = useGLTF('/models/mfb/1energy-ring/serpent.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="serpent" 
        geometry={nodes.serpent.geometry} 
        material={nodes.serpent.material}
        userData={{ name: 'serpent' }} 
      >
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/1energy-ring/serpent.glb')
