/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Model Created by: ericgallant24 https://www.thingiverse.com/ericgallant24/designs
*/

import * as THREE from 'three'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
    nodes: {
        libra: THREE.Mesh
    }
    materials: {}
}

export function Libra(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/mfb/1energy-ring/libra.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="libra"
        geometry={nodes.libra.geometry}
        material={nodes.libra.material}
        userData={{ name: 'libra' }}
      >
        <MeshTransmissionMaterial samples={1} resolution={128} transmission={0.3} roughness={0.3} />
        {/* <meshStandardMaterial roughness={0.1}/> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/1energy-ring/libra.glb')

