/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CW_Striker: THREE.Mesh
  }
  materials: {}
}

export function Striker(props: JSX.IntrinsicElements['group'] & {children?: React.ReactNode}) {
  const { nodes } = useGLTF('/models/mfb/1energy-ring/striker.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CW_Striker.geometry} material={nodes.CW_Striker.material}>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mfb/1energy-ring/striker.glb')
