/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import * as THREE from 'three'
import { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { Canvas as FabricCanvas } from 'fabric';

type GLTFResult = GLTF & {
    nodes: {
        death_gargoyl: THREE.Mesh
        wing_1: THREE.Mesh
        wing_2: THREE.Mesh
        eye_1: THREE.Mesh
        eye_2: THREE.Mesh
    }
    materials: {}
};

export function FabricPanel({ onTexture }: { onTexture: (t: THREE.CanvasTexture) => void }) {
    const fabricRef = useRef<FabricCanvas | null>(null)

    const init = (el: HTMLCanvasElement | null) => {
        if (!el || fabricRef.current) return
        const fc = new FabricCanvas(el, {
            isDrawingMode: true,
            width: el.parentElement?.clientWidth ?? 300,
            height: el.parentElement?.clientHeight ?? 500,
            backgroundColor: '#1a1a2e',
        })
        fabricRef.current = fc
        const tex = new THREE.CanvasTexture(fc.getElement())
        tex.flipY = false
        onTexture(tex)
        fc.on('after:render', () => { tex.needsUpdate = true })
    }

    const setColor = (c: string) => { if (fabricRef.current?.freeDrawingBrush) fabricRef.current.freeDrawingBrush.color = c }
    const setWidth = (w: number) => { if (fabricRef.current?.freeDrawingBrush) fabricRef.current.freeDrawingBrush.width = w }
    const clear = () => {
        const fc = fabricRef.current
        if (!fc) return
        fc.clear(); fc.backgroundColor = '#1a1a2e'; fc.renderAll()
    }

    return (
        <div style={{ width: '25%', height: '100%', display: 'flex', flexDirection: 'column', borderRight: '1px solid #333', background: '#111' }}>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, padding: '10px 8px', borderBottom: '1px solid #333' }}>
                <span style={{ color: '#aaa', fontSize: 11, width: '100%' }}>BRUSH COLOR</span>
                {['#ffffff', '#ff4444', '#44aaff', '#ffdd44', '#44ff99'].map(c => (
                    <div key={c} onClick={() => setColor(c)} style={{ width: 24, height: 24, borderRadius: '50%', background: c, cursor: 'pointer', border: '2px solid #555' }} />
                ))}
                <span style={{ color: '#aaa', fontSize: 11, width: '100%', marginTop: 4 }}>BRUSH SIZE</span>
                {[2, 6, 12, 20].map(s => (
                    <button key={s} onClick={() => setWidth(s)} style={{ background: '#222', color: '#ccc', border: '1px solid #444', borderRadius: 4, padding: '2px 8px', cursor: 'pointer', fontSize: 12 }}>{s}px</button>
                ))}
                <button onClick={clear} style={{ marginTop: 6, width: '100%', background: '#3a1a1a', color: '#ff6666', border: '1px solid #662222', borderRadius: 4, padding: '4px 0', cursor: 'pointer', fontSize: 12 }}>Clear</button>
            </div>
            <div style={{ flex: 1, overflow: 'hidden', position: 'relative' }}>
                <canvas ref={init} />
            </div>
        </div>
    )
}


export function DeathGargoyl({
    texture,
    ...props
}: JSX.IntrinsicElements['group'] & { texture: THREE.CanvasTexture | null }) {
    const { nodes } = useGLTF('/models/death_gargoyl.glb') as unknown as GLTFResult

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.death_gargoyl.geometry}>
                <mesh geometry={nodes.eye_1.geometry} position={[0, 0.01, 0]}>
                    <meshStandardMaterial color="#FFD700" />
                </mesh>
                <mesh geometry={nodes.eye_2.geometry} position={[0, 0.01, 0]}>
                    <meshStandardMaterial color="#FFD700" />
                </mesh>
                <mesh geometry={nodes.wing_1.geometry} position={[0, 0.1, 0]}>
                    <meshStandardMaterial color="#95989a" map={texture ?? null} />
                </mesh>
                <mesh geometry={nodes.wing_2.geometry} position={[0, 0.01, 0]}>
                    <meshStandardMaterial color="#95989a" map={texture ?? null} />
                </mesh>
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/death_gargoyl.glb')
