/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Death_Gargoyl: THREE.Mesh
  }
  materials: {}
}

export function DG(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/public/models/dg.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Death_Gargoyl"
        geometry={nodes.Death_Gargoyl.geometry}
        material={nodes.Death_Gargoyl.material}
        userData={{ name: 'Death_Gargoyl' }}
      />
    </group>
  )
}

useGLTF.preload('/public/models/dg.glb')
